apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: itemeyes-web
spec:
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: gcr.io/itemeyeskubernetes/itemeyes:v1
          name: itemeyes-web
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DB_HOST
              value: 127.0.0.1:3306
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command: ["/cloud_sql_proxy",
                    "-instances=itemeyes-199123:us-central1:itemeyes=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: cloudsql
          emptyDir:
