# yaml file for Kubernetes #2 (itemeyes)

apiVersion: v1
kind: Deployment
metadata:
  name: ItemEyes-Kubernetes
spec:
  template:
    metadata:
      labels:
        app: web
  spec:
    containers:
      - name: itemeyes-web
        ports:
          - containerPort: 80
            protocol: TCP
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-db-credentials
                key: password
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=itemeyes-199123:us-central1:itemeyes=tcp:3306,"
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
    volumes:
      - name: cloudsql-instance-credentials
        secrets:
          secretName: cloudsql-instance-credentials
      - name: cloudsql
        emptyDir:
